// Webcams públicas de puntos calientes. Priorizamos streams YouTube live 24/7
// (embeddables) y sitios oficiales (ports, marinas). URLs verificadas manualmente.

export const WEBCAMS = [
  {
    id: "ceuta-24-7",
    label: "Ceuta · Puerto y Estrecho de Gibraltar",
    zone: "gibraltar",
    embed: "https://www.youtube.com/embed/al9kIbbTaUg?autoplay=1&mute=1",
    watchUrl: "https://www.youtube.com/watch?v=al9kIbbTaUg",
    provider: "YouTube live · SkylineWebcams / Ceuta",
    note: "vista panorámica 24/7 sobre el puerto de Ceuta, heliport y tráfico marítimo del Estrecho",
    priority: true,
  },
  {
    id: "gibraltar-strait-earthcam",
    label: "Estrecho de Gibraltar · Earth Cam",
    zone: "gibraltar",
    embed: "https://www.youtube.com/embed/hrBG-y3fw-U?autoplay=1&mute=1",
    watchUrl: "https://www.youtube.com/watch?v=hrBG-y3fw-U",
    provider: "YouTube live · EarthCam",
    note: "estrecho de Gibraltar donde Atlántico y Mediterráneo se encuentran",
    priority: true,
  },
  {
    id: "gibraltar-town-waterfront",
    label: "Gibraltar · Waterfront",
    zone: "gibraltar",
    embed: "https://www.youtube.com/embed/R-X4n7DDejg?autoplay=1&mute=1",
    watchUrl: "https://www.youtube.com/watch?v=R-X4n7DDejg",
    provider: "YouTube live",
    note: "vista al Peñón y bahía de Algeciras",
  },
  {
    id: "ceuta-skylinewebcams",
    label: "Ceuta · SkylineWebcams",
    zone: "gibraltar",
    embed: null,
    watchUrl: "https://www.skylinewebcams.com/en/webcam/espana/ceuta/ceuta/ceuta.html",
    provider: "SkylineWebcams",
    note: "vista alternativa de Ceuta, iframe no permitido, abrir en nueva pestaña",
  },
  {
    id: "alcaidesa-marina",
    label: "La Línea · Alcaidesa Marina",
    zone: "gibraltar",
    embed: null,
    watchUrl: "https://alcaidesamarina.com/en/services/webcam/",
    provider: "Alcaidesa Marina · La Línea de la Concepción",
    note: "vista al Peñón desde el lado español de la frontera",
  },
  {
    id: "ceuta-worldcam",
    label: "Ceuta · Worldcam",
    zone: "gibraltar",
    embed: null,
    watchUrl: "https://worldcam.eu/webcams/europe/spain/21667-ceuta-strait-of-gibraltar",
    provider: "Worldcam",
    note: "agregador con múltiples vistas de Ceuta y el Estrecho",
  },
  {
    id: "bosphorus-live",
    label: "Bósforo · Estambul",
    zone: "mar-negro",
    embed: "https://www.youtube.com/embed/qXRYokWh3rU?autoplay=1&mute=1",
    watchUrl: "https://www.youtube.com/watch?v=qXRYokWh3rU",
    provider: "YouTube live",
    note: "único paso naval al Mar Negro, tráfico bajo Convención de Montreux",
    priority: true,
  },
  {
    id: "kaohsiung-port",
    label: "Kaohsiung · Puerto (Taiwán)",
    zone: "taiwan",
    embed: null,
    watchUrl: "https://www.webcamtaxi.com/en/taiwan/kaohsiung/port-warehouse-kw2-cam.html",
    provider: "WebcamTaxi",
    note: "puerto militar y comercial en costa suroeste de Taiwán",
  },
];
